### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by HyperBrain** [ktonon/elm-serverless#13]
The build specific modules can be upgraded to their recent versions:
```
serverless-webpack: 5.1.5
webpack: 4.6.x
```

However, this requires some changes in the `serverless.yml` and more important, the `webpack.config.js` files. For a sample webpack configuration with Webpack 4.x see the `babel-webpack-4` folder in the `serverless-webpack` examples.
Also, the `babel-loader` has to be updated to at least 7.1.3 for webpack 4.

**Comment by ktonon** [comment]
Thanks for letting me know about this and sorry for taking so long to reply. I will follow up in the next two weeks. I'll make sure to check for the latest version as the info in the issue might already be out of date.

**Comment by ktonon** [comment]
This fork is no longer maintained. Please see [rupertlssmith/elm-serverless](https://github.com/rupertlssmith/elm-serverless) for updates which apply to elm >= 0.19
