### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by Maxim-Filimonov** [ktonon/elm-serverless#16]
Hi,
I'm really keen to try to use your package. However, I couldn't install it with elm 0.19. Is it depending on some features which have been removed from 0.19 or can I help with the upgrade?

**Comment by ktonon** [comment]
This fork is no longer maintained. Please see [rupertlssmith/elm-serverless](https://github.com/rupertlssmith/elm-serverless) for updates which apply to elm >= 0.19
