### ISSUE TITLE
Elm 0.19 and future plans?

### ISSUE THREAD

**Issue by rupertlssmith** [ktonon/elm-serverless#18]
Hi @ktonon , I missed this project on Elm 0.19 as I was using it with 0.18 and finding it to be a great way of writing lambda functions for AWS.

I have created a PR that upgrades to 0.19, completing the work started by ream88.

I don't know if you want to go on with this project and maintaining it under 0.19 or not? Just considering my options on how best to get my upgrade published, as I could always just fork it. Not sure yet if I will just continue to use it as is, or if I would like to make some more substantial changes and take it in a new direction, so thought it best to get your thoughts first.

**Comment by ktonon** [comment]
Hello @rupertlssmith 
I'd be happy to hand-off the project to you. I no longer find time to work on it, but I'm happy that some people find it useful. If you are ok with it, I'll update the README header to point to your fork for elm 0.19 or greater.

**Comment by rupertlssmith** [comment]
Ok, I'll take it forward and keep it alive - and thanks for having the idea and bringing it this far.
